import SpiderGallery, { PhotoCredits } from './spider-gallery';
import { ArrowUpRight, ArrowRight, ShieldCheck, Bug, School, ScanSearch, Fence, Leaf, Mouse, Droplets, Check, BookOpen } from 'lucide-react';
const pests = [
  { icon: Bug, title: 'Ants & cockroaches', en: 'FOOD & WATER', text: 'Crumbs and accessible water attract unwanted visitors. Pay attention to eating areas, trash bins, and storage corners.', action: 'Seal food and clean up crumbs.' },
  { icon: Mouse, title: 'Rodents', en: 'ENTRY POINTS & SHELTER', text: 'Gaps under doors and clutter can provide access and shelter. Tell a teacher about gnaw marks or suspected rodent activity.', action: 'Organize supplies and report signs.' },
  { icon: Droplets, title: 'Mosquitoes', en: 'STANDING WATER', text: 'Many mosquitoes breed in standing water. Plant saucers, discarded containers, and poorly drained areas deserve attention.', action: 'Report standing water to school staff.' },
];
const questions = [
  ['Does seeing one pest mean we need to spray?', 'Not necessarily. Identify it, monitor activity, and decide whether it is causing a problem. Integrated pest management uses evidence to choose an appropriate response.'],
  ['What should I do if I see ants in class?', 'Tell your teacher where and when you saw them. Check for crumbs or open food, and clean up as directed. Students should not use pesticides.'],
  ['Are spiders insects?', 'No. Spiders are arachnids: they have eight legs and two main body regions. Insects have six legs. Many spiders help by eating other small animals, including pest insects.'],
  ['Are brown recluse spiders common in Pomona?', 'No. UC IPM reports no established breeding populations of the brown recluse in California. Other recluse species occur in southeastern California deserts. Do not identify a spider or diagnose a bite from a skin mark alone.'],
  ['What if someone may have been bitten?', 'Tell a teacher or school nurse immediately. A suspected black widow bite needs prompt medical advice. Do not try to catch the spider; let an adult arrange help.'],
  ['Can students set traps or use insecticides?', 'No. Observe, record, keep shared spaces tidy, and report concerns. Pesticides, traps, suspected rodent droppings, and spider removal belong with designated school staff or qualified professionals.'],
];
export default function Home() { return <>
  <a className="skip" href="#main">Skip to main content</a>
  <div className="topbar"><span>Pomona, California · A healthier campus starts with us.</span><span>OBSERVE. PREVENT. PROTECT.</span></div>
  <header className="nav wrap"><a className="brand" href="#" aria-label="Campus Pest Aware home"><ShieldCheck size={37}/><span>Campus Pest Aware<span className="brand-sub">POMONA · CLASSROOM EDITION</span></span></a><nav aria-label="Main navigation"><a href="#pests">Meet the pests</a><a href="#spiders">Spiders</a><a href="#ipm">Our approach</a><a href="#questions">Q&A</a></nav><a className="button small" href="#action">Take action <ArrowUpRight size={18}/></a></header>
  <main id="main">
    <section className="hero wrap"><div className="hero-copy"><div className="eyebrow"><span className="dot"/> PEST CONTROL · POMONA, CA</div><h1>Fewer pests.<br/>A healthier<br/><em>place to learn.</em></h1><p>Get to know the small creatures around our campus. Learn how observation, everyday habits, and thoughtful prevention help protect our shared spaces.</p><div className="hero-actions"><a className="button lime" href="#spiders">Explore local spiders <ArrowUpRight size={20}/></a><a className="text-link" href="#pests">Meet the pests <ArrowRight size={18}/></a></div><div className="hero-note"><BookOpen size={21}/><span>Identify · Prevent · Report · Review</span></div></div><div className="hero-image"><img src="/ant.jpg" alt="Close-up of an ant on a green leaf" width="1800" height="1200" fetchPriority="high"/><div className="image-label"><span className="dot"/> SMALL CREATURES. BIG QUESTIONS.</div><div className="image-card"><Leaf size={31}/><div><strong>Look closer.<br/>Think first.</strong><span>Not every insect is a pest.</span></div></div></div></section>
    <div className="principles wrap"><span><ScanSearch/> Observe & identify</span><span><Leaf/> Prevention first</span><span><Fence/> Keep entry points closed</span><span><School/> Work together</span></div>
    <section id="pests" className="section wrap"><div className="section-heading"><div><p className="eyebrow">MEET THE PESTS</p><h2>Why do they<br/>come to campus?</h2></div><p>Food, water, and shelter attract many pests.<br/>Change the conditions. Reduce the invitation.</p></div><div className="services">{pests.map(({icon:Icon,title,en,text,action},i)=><article className="service" key={title}><div className="service-top"><Icon size={33} strokeWidth={1.4}/><span>0{i+1}</span></div><h3>{title}</h3><p>{text}</p><div className="service-bottom"><span>{en}</span></div><p className="pest-action">Your part: {action}</p></article>)}</div><p className="source-note">A pest is a matter of context: a creature may need management when it affects health, property, or everyday activities. Many insects support pollination, decomposition, and natural pest control.</p></section>
    <section id="spiders" className="spider-section"><div className="wrap"><div className="section-heading"><div><p className="eyebrow">LOCAL FOCUS / POMONA, CALIFORNIA</p><h2>Share the outdoors.<br/>Keep spiders out of reach.</h2></div><p>Most spiders help control insects.<br/>Know when to give them space.</p></div><p className="spider-intro">Meet everyday spider neighbors and learn which sightings to report. This guide uses California and Los Angeles-area references, not reports of an infestation at any particular school.</p><SpiderGallery/><div className="spider-plan"><div><h3>Students: notice & report</h3><p>Keep hands out of hidden spaces. Tell a teacher about spiders or egg sacs near seating and play areas. Leave removal to school staff.</p></div><div><h3>School staff: prevent & monitor</h3><p>Reduce clutter, seal gaps, repair screens, and check sheltered outdoor fixtures. Arrange web removal and follow-up inspections. Routine spraying alone does not provide lasting control.</p></div></div><p className="source-note">Regional guidance: <a href="https://ipm.ucanr.edu/home-and-landscape/widow-spiders-and-their-relatives/" target="_blank" rel="noreferrer">UC IPM — Widow Spiders and Their Relatives ↗</a> · <a href="https://ipm.ucanr.edu/home-and-landscape/spiders/" target="_blank" rel="noreferrer">UC IPM — Spiders ↗</a></p></div></section>
    <section id="ipm" className="approach"><div className="wrap approach-grid"><div><p className="eyebrow">INTEGRATED PEST MANAGEMENT</p><h2>Good pest care<br/>starts with prevention.</h2><p>Integrated pest management (IPM) combines observation, environmental improvements, and treatment when needed. It reduces reliance on routine spraying and checks whether the plan works.</p><a href="#action" className="button lime">Find your next step <ArrowUpRight size={20}/></a></div><div className="steps">{[['01','Identify & record','What did you see? Where and when? Keep your distance, note the details, and tell a teacher.'],['02','Prevent & respond','Remove food scraps and water sources. Staff can repair entry points and select an appropriate response when the evidence shows one is needed.'],['03','Review & improve','School staff monitor whether the problem is improving. If activity continues, revisit the cause and adjust the plan.']].map(([n,t,d])=><div className="step" key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div><Check size={20}/></div>)}</div></div></section>
    <section id="questions" className="section wrap faq"><div><p className="eyebrow">THINK & DISCUSS</p><h2>Your questions.<br/>A little clarity.</h2><p className="source-note">Discuss with a partner, then open each answer.</p></div><div className="answers">{questions.map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></section>
    <section id="action" className="contact wrap"><div><p className="eyebrow">SMALL ACTIONS, BIG DIFFERENCE</p><h2>Be a campus<br/>caretaker.</h2><p className="source-note">Classroom challenge: observe one area with your teacher and suggest one way to prevent pests.</p></div><div className="contact-copy"><ul className="action-list">{['Clean eating areas and keep food in sealed containers.','Put litter in the right bin and keep shared spaces tidy.','Report leaks, standing water, and gaps around doors.','Report pest signs and spiders; do not touch or chase them.'].map(t=><li key={t}><Check/>{t}</li>)}</ul><div className="class-prompt"><strong>GROUP DISCUSSION</strong><p>You notice a web beneath an outdoor bench in Pomona. What should students do, and what should school staff check?</p></div></div></section>
    <section className="references wrap" aria-label="Learning resources"><h3>Keep exploring</h3><a href="https://nhm.org/socal-webs" target="_blank" rel="noreferrer">Natural History Museum: SoCal Webs ↗</a><a href="https://ipm.ucanr.edu/home-and-landscape/common-garden-spiders/" target="_blank" rel="noreferrer">UC IPM: Common garden spiders ↗</a><p>Classroom education for Pomona, California. School staff should adapt pest management to the site and applicable local requirements. This is not an official school or city website.</p><a href="https://ipm.ucanr.edu/home-and-landscape/spiders/" target="_blank" rel="noreferrer">UC IPM: Spiders ↗</a><a href="https://ipm.ucanr.edu/home-and-landscape/widow-spiders-and-their-relatives/" target="_blank" rel="noreferrer">UC IPM: Widow spiders ↗</a><a href="https://www.epa.gov/safepestcontrol/integrated-pest-management-ipm-principles" target="_blank" rel="noreferrer">EPA: IPM principles ↗</a><a href="https://www.epa.gov/pesticides/epa-releases-update-popular-school-integrated-pest-management-publication" target="_blank" rel="noreferrer">EPA: School pest management ↗</a><a href="https://www.cdc.gov/mosquitoes/mosquito-control/index.html" target="_blank" rel="noreferrer">CDC: Mosquito control ↗</a><PhotoCredits/></section>
  </main><footer className="wrap"><a className="brand" href="#"><ShieldCheck size={30}/><span>Campus Pest Aware<span className="brand-sub">LEARN · CARE · ACT</span></span></a><span>Pomona, California · Classroom edition</span><a href="https://unsplash.com/photos/black-ant-on-green-leaf-xXrVvepbzRI" target="_blank" rel="noreferrer">Photo by Shannon Potter ↗</a></footer>
</>; }
